site_name: GlassFlow Python SDK Docs
site_author: GlassFlow
site_description: Python SDK Reference for GlassFlow

theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.path
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/glassflowdev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/glassflow-dev/
    - icon: fontawesome/solid/paper-plane
      link: mailto:help@glassflow.dev

nav:
  - Home: index.md
  - Python SDK Docs: reference.md
  - "User Guide ↗️" : 'https://learn.glassflow.dev/docs'
  - "GlassFlow Blog ↗️" : 'https://learn.glassflow.dev/blog'
  - "User Guide ↗️" : 'https://docs.glassflow.dev/'
  - "GlassFlow Blog ↗️" : 'https://www.glassflow.dev/blog'

plugins:
  - mkdocstrings
  - search