site_name: GlassFlow Python SDK
site_author: GlassFlow
site_description: Python SDK Reference for GlassFlow

theme:
  name: "material"
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - content.code.copy
    - navigation.path
    - navigation.footer
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/glassflowdev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/glassflow-dev/
    - icon: fontawesome/solid/paper-plane
      link: mailto:help@glassflow.dev

nav:
  - Home:
    - Welcome to GlassFlow: index.md
    - Pipeline and Space Management: pipeline_management.md
    - Publish and Consume events: publish_and_consume.md
    - "User Guide ↗️" : 'https://www.glassflow.dev/docs'
    - "GlassFlow Blog ↗️" : 'https://www.glassflow.dev/blog'
  - API Reference:
    - reference.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          import:
            - url: https://docs.python-requests.org/en/master/objects.inv
              domains: [ std, py ]
          options:
            members_order: source
            separate_signature: true
            filters: [ "!^_" ]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

  - admonition

  - toc:
      title: Page contents
      permalink: true
