name: build documentation and publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install lazydocs
      - run: pip install .
      - name: build documentation
        run: python generate_docs.py
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: docs/api-docs
          destination-github-username: 'glassflow'
          destination-repository-name: 'glassflow-python-sdk-docs'
          user-email: ashish@glassflow.dev
          target-branch: main
