name: Test GlassFlow Python SDK


env:
  PROJECT_ID: glassflow-dataforge
  SERVICE_ACCOUNT: 'github-ci-cd@glassflow-dataforge.iam.gserviceaccount.com'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/585858172927/locations/global/workloadIdentityPools/github/providers/github-repo-provider'

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run pytest tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: pip install -e .[dev]

      - name: Run Integration Tests
        run: pytest tests/glassflow/integration_tests/
        env:
          PIPELINE_ID: ${{ secrets.PIPELINE_ID }}
          PIPELINE_ACCESS_TOKEN: ${{ secrets.PIPELINE_ACCESS_TOKEN }}

  checks:
    name: Run code checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: pip install -e .[dev]

      - name: Run isort
        run: isort .

      - name: Run linter and code formatter
        run: ruff check .
