name: Smoke Test

on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        id: setup-python
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@e58605a9b6da7c637471fab8847a5e5a6b8df081 # v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up venv
        run: |
          uv venv --python ${{ steps.setup-python.outputs.python-path }}

      - name: Install dependencies
        run: |
          uv pip install -e .[test]

      - name: Run tests
        run: |
          uv run pytest
